#! /bin/bash

help() {
    cat << UsageMessage

guesthub utilities

Usage: ./run [command]

Commands:
    run
    Starts the server in production mode

    dev
    Starts the server in development mode

    reset_db
    Resets the database

UsageMessage
}

updateHosts() {
    # Define the entries to be added if missing
    local entries=(
        "127.0.0.1 guesthub.local"
        "127.0.0.1 api.guesthub.local"
    )

    # Check and add each entry if it does not exist
    for entry in "${entries[@]}"; do
        if ! grep -q "$entry" /etc/hosts; then
            echo "Adding $entry to /etc/hosts"
            echo "$entry" | sudo tee -a /etc/hosts > /dev/null
        else
            echo "$entry already exists in /etc/hosts"
        fi
    done
}

run() {
    docker compose up --build
}

build() {
    docker compose build
}

dev() {
    updateHosts
    NODE_ENV=development docker compose up
}

reset_db() {
  docker compose run --rm postgres dropdb -h postgres -U guesthub guesthub --force
  docker compose run --rm postgres createdb -h postgres -U guesthub guesthub
}

clean_simulator() {
  xcrun simctl erase all
}

if declare -F "$1" > /dev/null; then
  $@
else
  echo "Unknown command: $1"
  help
fi